"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""


def solution():
    f_2 = 1
    f_1 = 2
    f = 0
    answer = f_1
    while f < 4000000:
        f = f_2 + f_1
        if f % 2 == 0:
            answer += f
        f_2 = f_1
        f_1 = f
    return answer
